Valid SUDUKO

In [1]:
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [10]:
b = np.sum(s,axis=0)

In [11]:
c = np.sum(s,axis=1)

In [12]:
for i in b:
    if i != 45:
        print('Suduko is invalid')
else:
    print('Suduko is Valid')

Suduko is Valid


In [13]:
for i in c:
    if i != 45:
        print('Suduko is invalid')
else:
    print('Suduko is Valid')

Suduko is Valid


In [ ]:
slice = s[0:3,0:3]
slice

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [16]:
for i in range(0,9,3):
    for j in range(0,9,3):
        slice = s[i:i+3,j:j+3]
        if(slice.sum()!=45):
            print('Not Valid')
else:
    print('Valid')

Valid


In [ ]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [18]:
data.shape

(5, 3)

In [21]:
d = np.mean(data,axis=0)
d[0]

np.float64(18.4)

In [22]:
np.mean(data[:,0])

np.float64(18.4)

In [23]:
data[:,1]

array([85, 92, 76, 65, 90])

In [26]:
data[:,2].max()
np.max(data[:,2])

np.int64(95)

In [28]:
bool_index = data[:,1] > 90
bool_index

array([False,  True, False, False, False])

In [29]:
data[bool_index]

array([[19, 92, 88]])

In [33]:
data[:,1] += 5

In [34]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [36]:
len(data[data[:,0] < 19])

3

In [38]:
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [39]:
# Atleast 80 in both subject
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [40]:
# Replace all Science marks < 75 to 0

data[:,2][data[:,2] < 75] = 0

In [41]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])