In [2]:
import numpy as np

In [3]:
# Array Creation
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [ ]:
np.array(a)
# We are trying to convert a hetrogenous list to array. What will happen
# np.array converts it into a singular data type U32/Unicode basically like a string

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [ ]:
b = [1,2,3.5]
np.array(b)
# NOW IT CONVERTED INTO FLOAT

array([1. , 2. , 3.5])

In [9]:
# Multi dimensional array
# lets try to create a multidim list
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)
# This is actual multi-dimensinal structure
# Tensors - structure like 2 dim , 3 dim, 4 dim .....

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr = np.arange(1,10)
arr2 = np.arange(1,10,2)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr2

array([1, 3, 5, 7, 9])

In [18]:
arr3 = np.zeros(6)
arr3

array([0., 0., 0., 0., 0., 0.])

In [20]:
arr4 = np.zeros((4,8))
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr5 = np.ones((6,6))
arr5

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,3)
arr
# Provides certain number of elements with equal spacing beetween them

array([1., 3., 5.])

In [ ]:
np.linspace(1,5,5)
# Start, End, No. of elements

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(1,5,10)
# 10 numbers between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace(1,5,100)
# Last and first element will be start and stop

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

Rnadom Number Generation

In [ ]:
arr = np.random.rand(5)
arr
# Values come bw 0 and 1 - Normalization

array([0.54844977, 0.4746247 , 0.4834016 , 0.13169462, 0.97656473])

In [ ]:
arr = np.random.randn(10)
arr
# Values are from -3 to 3 - Standarlization

array([-2.45128483, -0.03013381,  1.06811246, -0.5484355 ,  0.27228748,
        1.48742713,  0.37169743, -0.22408903, -0.92583899,  0.04430577])

In [ ]:
np.random.randint(6)
# Gives random no from 0 to 6

1

In [ ]:
np.random.randint(10,20,5)
# Start, End, No of Element

array([13, 17, 19, 10, 13], dtype=int32)

Array Attributes

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
# | Attributes                | Methods                   |
# | ------------------------- | ------------------------- |
# | Store data                | Perform actions           |
# | Variables of class/object | Functions of class/object |
# | Accessed without `()` Not Called    | Called using `()`         |


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape
# shape is an attribute

(3, 3)

In [38]:
arr.size

9

In [39]:
arr.dtype

dtype('int64')

Array Methods

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()
#It is an inbuilt function 

np.int64(45)

In [ ]:
np.sum(arr,axis=0)
# Array methods using np axis 0 refers to row wise

array([12, 15, 18])

In [44]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [45]:
arr.mean()

np.float64(5.0)

In [46]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()
# Index of maximum element

np.int64(8)

Reshaping and Resizing

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
# Element count was 30 so for rshaping we need to maintain count 5*6
arr = arr.reshape((5,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

NUMPY INDEXING AND SLICING OF VECTORS

In [56]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
arr[6]

np.int64(17)

In [59]:
arr[1:5]

array([12, 13, 14, 15])

In [60]:
arr[3::2]

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [61]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [62]:
arr[0]

array([1, 2, 3, 4, 5])

In [64]:
arr[0,0]

np.int64(1)

In [68]:
# Want 2 3 7 8
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [69]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [70]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [75]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [77]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

NUMPY OPERATIONS/ ARRAY OPERATIONS

Arithematic Operations

In [78]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2
# Size must be same - could not broadcast

array([-5, -5, -5, -5, -5])

In [80]:
a1 // a2

array([0, 0, 0, 0, 0])

In [81]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

BroadCasting

In [82]:
l = [10,20,30,40]
arr = np.array(l)

In [83]:
for i in l:
    print(i+10)

20
30
40
50


In [ ]:
arr + 10
# So easy in array - Broadcasting

array([20, 30, 40, 50])

In [86]:
a1 = np.arange(1,26).reshape(5,5)
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [87]:
a1 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [88]:
a1 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow Copy

In [89]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [92]:
slice = a[:5]
slice = slice * 10

In [93]:
slice

array([10, 20, 30, 40, 50])

In [ ]:
a
# No changes in a if changes in its slice
# This refers to Shallow Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
b = a

In [96]:
b[0] = 99

In [97]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [98]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [99]:
# Here a also gets changed when we change in b
# When we fully copy an array to another variable , the location is passed to other variable, so changes in b happens in a also

# We need to create a shallow copy
c = b.copy()

In [100]:
c[0] = 100
c

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
b 
# No change in b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [103]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [104]:
A

array([[1, 2],
       [3, 4]])

In [105]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A*B
# Here it multiplied the corresponding matrices but thats not what actually matrix multiply

array([[ 5, 12],
       [21, 32]])

In [ ]:
A @ B 
# True matrix multiplication

array([[19, 22],
       [43, 50]])

In [108]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

STACKING ARRAY

In [ ]:
# Works on Matrix ONly
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
np.vstack((a,b))
# Stack row wise

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))
# Stack horizontal wise

array([1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
np.column_stack((a,b))
# Stack col wise

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [114]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)
# np.hsplit(c,3) - This will give error as no equal split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [116]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]